# Vkusno Bot
FROM python:3.11-slim

WORKDIR /app/bot

COPY bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY bot/ ./
COPY data/ ../data/

VOLUME ["/app/bot/logs"]

CMD ["python", "bot_v2_fixed.py"]
