version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: vkusno_bot
    restart: unless-stopped
    volumes:
      - ./bot/logs:/app/bot/logs
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - vkusno_network

  site:
    build:
      context: .
      dockerfile: Dockerfile.site
    container_name: vkusno_site
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - vkusno_network

networks:
  vkusno_network:
    driver: bridge
